if ENV["ENV"] === "production"
  PARSE_ID = ENV["PARSE_ID"]
  PARSE_REST_API = ENV["PARSE_REST_API"]
  DB_HOST = ENV["DB_HOST"]
  DB = ENV["DB"]
  DB_USERNAME = ENV["DB_USERNAME"]
  DB_PASSWORD = ENV["DB_PASSWORD"]
else
  PARSE_ID = ENV["UAT_PARSE_ID"]
  PARSE_REST_API = ENV["UAT_PARSE_REST_API"]
  DB_HOST = ENV["UAT_DB_HOST"]
  DB = ENV["UAT_DB"]
  DB_USERNAME = ENV["UAT_DB_USERNAME"]
  DB_PASSWORD = ENV["UAT_DB_PASSWORD"]
end
